### ISSUE TITLE
Error running syncdb during vagrant setup

### ISSUE THREAD

**Issue by Osmose** [mozilla/lumbergh#121]
When running `vargrant up` to set up a vagrant instance of the project, I get the following error:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet apply --manifestdir /tmp/vagrant-puppet-3/manifests --detailed-exitcodes /tmp/vagrant-puppet-3/manifests/vagrant.pp

Stdout from the command:

warning: Could not retrieve fact fqdn
notice: /Stage[main]/Init/Exec[update_apt]/returns: executed successfully
notice: /Stage[main]/Init/Package[python-software-properties]/ensure: ensure changed 'purged' to 'present'
notice: /Stage[main]/Memcached/Package[memcached]/ensure: ensure changed 'purged' to 'present'
notice: /Stage[main]/Mysql/Package[mysql-server]/ensure: ensure changed 'purged' to 'present'
notice: /Stage[main]/Mysql/Package[libmysqld-dev]/ensure: ensure changed 'purged' to 'present'
notice: /Stage[main]/Python/Package[python-wsgi-intercept]/ensure: ensure changed 'purged' to 'present'
notice: /Stage[main]/Python/Package[python-pip]/ensure: ensure changed 'purged' to 'present'
notice: /Stage[main]/Python/Package[python2.7-dev]/ensure: ensure changed 'purged' to 'present'
notice: /Stage[main]/Python/Exec[pip-install-compiled]/returns: executed successfully
notice: /Stage[main]/Python/Package[libapache2-mod-wsgi]/ensure: ensure changed 'purged' to 'present'
notice: /Stage[main]/Apache/Package[apache2-dev]/ensure: ensure changed 'purged' to 'present'
notice: /Stage[main]/Apache/File[/etc/apache2/sites-enabled/playdoh.conf]/ensure: defined content as '{md5}af1e43acf8f7ed9129ab1f23ec8ee4b2'
notice: /Stage[main]/Playdoh/Exec[create_mysql_database]/returns: executed successfully
err: /Stage[main]/Playdoh/Exec[syncdb]/returns: change from notrun to 0 failed: python ./manage.py syncdb --noinput returned 1 instead of one of [0] at /tmp/vagrant-puppet-3/manifests/classes/playdoh.pp:28
notice: /Stage[main]/Playdoh/Exec[sql_migrate]: Dependency Exec[syncdb] has failures: true
warning: /Stage[main]/Playdoh/Exec[sql_migrate]: Skipping because of failed dependencies
notice: Finished catalog run in 370.38 seconds
```

Afterwards, I SSHed into the box and ran `syncdb` manually, and got this:

```
vagrant@precise64:~/project$ ./manage.py syncdb --noinput
Traceback (most recent call last):
  File "./manage.py", line 23, in <module>
    manage.main()
  File "/home/vagrant/project/vendor/src/funfactory/funfactory/manage.py", line 143, in main
    execute_manager(current_settings)
  File "/home/vagrant/project/vendor-local/src/django/django/core/management/__init__.py", line 459, in execute_manager
    utility.execute()
  File "/home/vagrant/project/vendor-local/src/django/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/project/vendor-local/src/django/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/project/vendor-local/src/django/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/home/vagrant/project/vendor-local/src/django/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/home/vagrant/project/vendor-local/src/django/django/core/management/validation.py", line 103, in get_validation_errors
    connection.validation.validate_field(e, opts, f)
  File "/home/vagrant/project/vendor-local/src/django/django/db/backends/mysql/validation.py", line 14, in validate_field
    db_version = self.connection.get_server_version()
  File "/home/vagrant/project/vendor-local/src/django/django/db/backends/mysql/base.py", line 415, in get_server_version
    self.cursor().close()
  File "/home/vagrant/project/vendor-local/src/django/django/db/backends/__init__.py", line 317, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/vagrant/project/vendor-local/src/django/django/db/backends/mysql/base.py", line 387, in _cursor
    self.connection = Database.connect(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 188, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'lumbergh'@'localhost' (using password: YES)")
```

@koddsson wasn't able to reproduce this on his setup. I've made sure I'm using the latest vagrant version, as he is as well.

**Comment by bensternthal** [comment]
Closing - we have moved from vagrant to docker.
